apiVersion: v1
kind: Pod
metadata:
  name: vizdoom2018-grading-pod-debug
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: host
    image: localhost:5000/cig2017_host:latest
    volumeMounts:
    - name: shared-data
      mountPath: /crowdai
    command: ["/home/crowdai/run.sh"]
    # command: ["sleep"]
    # args: ["3600"]

  - name: submission-01
    image: localhost:5000/cig2017_random:latest
    command: ["/home/crowdai/run.sh"]
    # command: ["sleep"]
    # args: ["3600"]
    volumeMounts:
    - name: shared-data
      mountPath: /crowdai
  restartPolicy: Never
